name: idea_generator_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.2
  google_fonts: ^8.0.2           
  audioplayers: ^6.6.0           
  shared_preferences: ^2.5.4      
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0           
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/IdevioIcon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/cartoon-game-damage-alert-ni-sound-1-00-03.mp3
    - assets/icon/IdevioIcon.png
    - assets/icon/Idevio-192x192.png
    - assets/icon/Idevio-512x512.png
    - assets/icon/Idevio-maskable-192x192.png
    - assets/icon/Idevio-maskable-512x512.png